// Do not edit this file, it is auto-generated!

// Generated by qrust-gen
// Generator: GQSharedData
// Template:  qshareddata_cpp.mako
// Timestamp: 2016-07-29T10:06:49Z

#include <QtCore/QDir>

#include "common.h"

// CTOR

extern "C" void* _qrust_qdir_c_1() {
	return qshared2voidptr(QDir());
}

// MEMBER TRAMPOLINES

extern "C" void* _qrust_qdir_m_filePath(void* self, void* fileName)
{
	auto obj = voidptr2qshared<QDir>(self);
	return qshared2voidptr(obj.filePath(voidptr2qshared<QString>(fileName)));
}
extern "C" int _qrust_qdir_m_isRelative(void* self)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.isRelative();
}
extern "C" void* _qrust_qdir_m_canonicalPath(void* self)
{
	auto obj = voidptr2qshared<QDir>(self);
	return qshared2voidptr(obj.canonicalPath());
}
extern "C" int _qrust_qdir_m_mkpath(void* self, void* dirPath)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.mkpath(voidptr2qshared<QString>(dirPath));
}
extern "C" void _qrust_qdir_m_setPath(void* self, void* path)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.setPath(voidptr2qshared<QString>(path));
}
extern "C" int _qrust_qdir_m_makeAbsolute(void* self)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.makeAbsolute();
}
extern "C" void* _qrust_qdir_m_dirName(void* self)
{
	auto obj = voidptr2qshared<QDir>(self);
	return qshared2voidptr(obj.dirName());
}
extern "C" int _qrust_qdir_m_remove(void* self, void* fileName)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.remove(voidptr2qshared<QString>(fileName));
}
extern "C" void _qrust_qdir_m_refresh(void* self)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.refresh();
}
extern "C" int _qrust_qdir_m_mkdir(void* self, void* dirName)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.mkdir(voidptr2qshared<QString>(dirName));
}
extern "C" int _qrust_qdir_m_rmpath(void* self, void* dirPath)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.rmpath(voidptr2qshared<QString>(dirPath));
}
extern "C" void* _qrust_qdir_m_absolutePath(void* self)
{
	auto obj = voidptr2qshared<QDir>(self);
	return qshared2voidptr(obj.absolutePath());
}
extern "C" void* _qrust_qdir_m_absoluteFilePath(void* self, void* fileName)
{
	auto obj = voidptr2qshared<QDir>(self);
	return qshared2voidptr(obj.absoluteFilePath(voidptr2qshared<QString>(fileName)));
}
extern "C" int _qrust_qdir_m_exists0(void* self)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.exists();
}
extern "C" int _qrust_qdir_m_exists1(void* self, void* name)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.exists(voidptr2qshared<QString>(name));
}
extern "C" int _qrust_qdir_m_cdUp(void* self)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.cdUp();
}
extern "C" int _qrust_qdir_m_cd(void* self, void* dirName)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.cd(voidptr2qshared<QString>(dirName));
}
extern "C" void* _qrust_qdir_m_relativeFilePath(void* self, void* fileName)
{
	auto obj = voidptr2qshared<QDir>(self);
	return qshared2voidptr(obj.relativeFilePath(voidptr2qshared<QString>(fileName)));
}
extern "C" int _qrust_qdir_m_removeRecursively(void* self)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.removeRecursively();
}
extern "C" int _qrust_qdir_m_rename(void* self, void* oldName, void* newName)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.rename(voidptr2qshared<QString>(oldName), voidptr2qshared<QString>(newName));
}
extern "C" int _qrust_qdir_m_rmdir(void* self, void* dirName)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.rmdir(voidptr2qshared<QString>(dirName));
}
extern "C" void* _qrust_qdir_m_path(void* self)
{
	auto obj = voidptr2qshared<QDir>(self);
	return qshared2voidptr(obj.path());
}
extern "C" int _qrust_qdir_m_isReadable(void* self)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.isReadable();
}
extern "C" int _qrust_qdir_m_isRoot(void* self)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.isRoot();
}
extern "C" int _qrust_qdir_m_isAbsolute(void* self)
{
	auto obj = voidptr2qshared<QDir>(self);
	return obj.isAbsolute();
}


