// Do not edit this file, it is auto-generated!

// Generated by qrust-gen
// Generator: GModule
// Template:  lib_rs.mako
// Timestamp: 2016-08-07T09:35:27Z

#![feature(const_fn)]

extern crate libc;
extern crate qr_core;

mod qwidget;

pub use qwidget::*;
