[package]
name = "qr_widgets"
version = "0.1.0"
authors = ["Vojtech Kral <vojtech@kral.hk>"]
links = "qrust-widgets-glue"
build = "build.rs"

[build-dependencies]
cmake = "0.1"

[dependencies]
libc = "0.2.0"
qr_core = { path = "../qrust-core" }
